name: ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out protocol repo
        uses: actions/checkout@v5

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v5

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --ignore-workspace --frozen-lockfile

      - name: Build
        run: pnpm run build
